config/routes.rb
Rails.application.routes.draw do

  get '/admin', to: 'admin#index'
  get 'admin/logout', to: 'admin#destroy'
  post 'admin/login', to: 'admin#authorize'

  get 'results(.:format)', to: 'results#index'

  get 'results/races/:id(.:format)', to: 'results#manage', as: 'manage_result'

  get 'results/races/:race_id/stages/:id(.:format)', to: 'results#stage_results', as: 'stage_results'

  #new stage_effort 
  get 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/new(.:format)', to: 'stage_efforts#new', as: 'new_stage_effort'
  post 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts(.:format)', to: 'stage_efforts#create', as: 'stage_efforts'  
  get 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id/edit(.:format)', to: 'stage_efforts#edit', as: 'edit_stage_effort'
  put 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#update'
  patch 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#update', as: 'update_stage_effort'
  delete 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#destroy', as: 'destroy_stage_effort'

  resources :cyclists
  get '/auth', to: 'sessions#create'
  get '/token_exchange', to: 'sessions#get_token', as: 'get_token'
  get '/deauth', to: 'sessions#deauth'
  #get '/deauth', to: 'sessions#reset_token'
  #resources :stage_efforts

  get '/request/athlet', to: 'request#athlet', as: 'request_athlet'
  get '/request/activity', to: 'request#activity', as: 'request_activity'

  get '/sessions/race_result/:race_id', to: 'sessions#race_result', as: 'race_result'
  
  resources :races, path: '/admin/races' do
    resources :stages, except: :index do
      resources :segments
    end
    resources :rosters, only: [:index, :create, :destroy]
  end

  delete 'rosters/:race_id/cyclist/:id', to: 'rosters#destroy', as: 'delete_roster'
  post 'rosters/create/', to: 'rosters#create', as: 'create_roster'
   
  root 'sessions#get_token'
end

app/models/race.rb
class Race < ActiveRecord::Base
	default_scope {order('id')}
	
	has_many :rosters, dependent: :destroy	
	has_many :cyclists, through: :rosters
	has_many :stages, dependent: :destroy	

	#accepts_nested_attributes_for :cyclists , :allow_destroy =>true
	accepts_nested_attributes_for :rosters, :allow_destroy =>true
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :roster, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all.order('created_at DESC').reverse_order!   
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  def roster
  end 

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to races_path, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name, :description, :start_date, :end_date, :hashtag)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= simple_form_for(@race) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.text_area :description, size: '120x6' %>
    <%= f.input :hashtag %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Cancel', races_path, class: 'btn btn-default btn-cancel'  %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h3>Editing Race</h3>

<%= render 'form' %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>
<h3>
<span>Races</span>
<%= link_to 'New Race', new_race_path, class: 'btn btn-default btn-new' %>
</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Stages</th>    
      <th>Roster</th>  
      <th>Start Date</th>
      <th>End Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>        
        <td><%= link_to race.stages.count, race %></td>
        <td><%= link_to race.rosters.count, race_rosters_path(race) %></td>
        <td><%= race.stages.first.active_date if race.stages.first %></td>
        <td><%= race.stages.last.close_date if race.stages.last %></td>        
        <td><%= link_to 'Manage Results', manage_result_path(race) %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/races/new.html.erb
<h3>New Race</h3>

<%= render 'form' %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <u><%= @race.name %></u>
  <span>-</span>
  <span>Stages</span>
  <span><%= link_to 'Add Stage', new_race_stage_path(@race), class: 'btn btn-default btn-new' %></span>
</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Stage #</th>
      <th>Name</th>
      <th>Segments</th>
      <th>Active date</th>
      <th>Close date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @race.stages.each do |stage| %>
      <tr>
        <td><%= stage.stage_no %></td>
        <td><%= link_to stage.name, race_stage_path(@race, stage) %></td>
        <td><%= stage.segments.count %></td>
        <td><%= stage.active_date %></td>
        <td><%= stage.close_date %></td>        
        <td><%= link_to 'Edit', edit_race_stage_path(@race, stage) %></td>
        <td><%= link_to 'Delete', race_stage_path(@race, stage), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>