config/routes.rb
Rails.application.routes.draw do

  get '/admin', to: 'admin#index'
  get 'admin/logout', to: 'admin#destroy'
  post 'admin/login', to: 'admin#authorize'

  get 'results(.:format)', to: 'results#index'

  get 'results/races/:id(.:format)', to: 'results#manage', as: 'manage_result'

  get 'results/races/:race_id/stages/:id(.:format)', to: 'results#stage_results', as: 'stage_results'

  #new stage_effort 
  get 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/new(.:format)', to: 'stage_efforts#new', as: 'new_stage_effort'
  post 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts(.:format)', to: 'stage_efforts#create', as: 'stage_efforts'  
  get 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id/edit(.:format)', to: 'stage_efforts#edit', as: 'edit_stage_effort'
  put 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#update'
  patch 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#update', as: 'update_stage_effort'
  delete 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#destroy', as: 'destroy_stage_effort'

  resources :cyclists
  get '/auth', to: 'sessions#create'
  get '/token_exchange', to: 'sessions#get_token', as: 'get_token'
  get '/deauth', to: 'sessions#deauth'
  #get '/deauth', to: 'sessions#reset_token'
  #resources :stage_efforts

  get '/request/athlet', to: 'request#athlet', as: 'request_athlet'
  get '/request/activity', to: 'request#activity', as: 'request_activity'

  get '/sessions/race_result/:race_id', to: 'sessions#race_result', as: 'race_result'
  
  resources :races, path: '/admin/races' do
    resources :stages, except: :index do
      resources :segments
    end
    resources :rosters, only: [:index, :create, :destroy]
  end

  delete 'rosters/:race_id/cyclist/:id', to: 'rosters#destroy', as: 'delete_roster'
  post 'rosters/create/', to: 'rosters#create', as: 'create_roster'
   
  root 'sessions#get_token'
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
  	@races = Race.all
  end

  def manage
  	@race = Race.find(params[:id])
    #@cyclists = sort_cyclists_race(@race)
    #@sorted_cyclists_race = sort_cyclists_race(@race)
    @sorted_cyclists_race_stage = sort_cyclists_race_stage_list(@race)
  end

  def stage_results
  	@race = Race.find(params[:race_id])
  	@stage = @race.stages.find(params[:id])
  	@cyclists = @race.cyclists    
    @cyclists = sort_cyclists_stage(@cyclists, @stage)    
  end

  def edit
    @race = Race.find(params[:race_id])
    @stage = @race.stages.find(params[:stage_id])
    @cyclist = Cyclist.find(params[:id])
  end    

  def update
    @race = Race.find(params[:race_id])
    @stage = @race.stages.find(params[:stage_id])
    @cyclist = Cyclist.find(params[:id])
    @stage_effect = StageEffect.new
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/edit.html.erb
<h3><%= link_to @race.name, race_path(@race) %> &nbsp;-&nbsp; <%= link_to 'Manage Results', manage_result_path(@race) %> &nbsp;-&nbsp; <%= @stage.name %> &nbsp;-&nbsp; <%= @cyclist.name %></h3>

<%= simple_form_for(StageEffort.new) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :strava_activity_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>
<% today = Time.now %>
<%= today %>

<h3>Races</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= link_to race.name, manage_result_path(race) %></td>
        <td><%= race.description %></td>
        <td><%= race.stages.first.active_date if race.stages.first %></td>
        <td><%= race.stages.last.close_date if race.stages.last %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/results/manage.html.erb
<h3><%= link_to @race.name, race_path(@race) %> &nbsp;-&nbsp; Manage Results</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Stage#</th>
      <th>Name</th>
      <th>Results</th>
      <th>Start</th>
      <th>End</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @race.stages.each_with_index do |stage| %>
    <%
        stage_effort_count = 0
        @race.cyclists.each {|cyclist| stage_effort_count = stage_effort_count + 1 if cyclist.stage_efforts.find_by(stage_id: stage) } %>
      <tr>
        <td><%= stage.stage_no %></td>
        <td><%= link_to stage.name, race_stage_path(@race, stage) %></td>
        <td><%= stage_effort_count.to_s + '/' + @race.cyclists.count.to_s %></td>
        <td><%= stage.active_date %></td>
        <td><%= stage.close_date %></td>        
        <td><%= link_to 'Manage Results',  stage_results_path(@race, stage) %></td>        
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Refresh', request.original_url, class: 'btn btn-default' %>
<br>
<div class="row">
  <div class="col-md-3"><h3>Overall Leaderboard</h3></div>
  <div class="col-md-9">
    <h3>
      <button type="button" class="btn btn-default export-btn" data-toggle="modal" data-target="#myModal">
        Export
      </button>
    </h3>
  </div>
</div>
<div class="modal fade" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Leaderboard Export</h4>
      </div>
      <div class="modal-body">
        <textarea class="export-textarea" rows="30" cols="78">
          
        </textarea>
      </div>      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
  $('.export-btn').click(function(){
    var table_data = $('div.tab-pane.active table').html();
    var custom_style = "<style>\n .hftable { width:100%; border-collapse: collapse;}\n  th, td { text-align: left; border: 1px solid gray; padding: 5px; }\n</style>\n";
    table_data = custom_style + "<table class='hftable'>" + table_data + "</table>";
    $('.export-textarea').text(table_data);
  });
</script>
<ul class="nav nav-tabs">
  <% @sorted_cyclists_race_stage.each_with_index do |item, index| %>
    <li class = "<% if index == 0 %>active<% end %>"><a data-toggle="tab" href="#stage<%= index %>" >Stage <%= index + 1 %></a></li>
  <% end %>
</ul>

<div class="tab-content">
  <% @sorted_cyclists_race_stage.each_with_index do |item, index| %>
    <div id="stage<%= index %>" class="tab-pane fade in <% if index == 0 %> active <% end %>">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Place</th>
            <th>Points</th>
            <th>Name</th>
            <th>Total time</th>
          </tr>
        </thead>

        <tbody>
          <% 
            index_tmp = 0
            total_points_temp = 0
            index_dnf = 0
            flag = 0
          %>
          <% item.each_with_index do |item_x, index_x| %>    
            <tr>      
            <%
            if total_points_temp == 0 or total_points_temp > item_x['total_points']
              total_points_temp = item_x['total_points']
              index_tmp = index_x + 1
            end

            if item_x['total_time'] == "DNF" and flag == 0
              index_dnf = index_x + 1
              flag = 1
            end

            %>
              <td>
              <% if item_x['total_time'] != "DNF" %>
                <%= index_x + 1 %>
              <% else %>
                <%= index_dnf %>
              <% end %>
              </td>
              <td>
              <%= item_x['total_points'] %>
              </td>      
              <td><%= item_x['cyclist'].name %></td>
              <td>
                <% if item_x['total_time'] != "DNF" %>
                <%= Time.at(item_x['total_time']).utc.strftime('%H:%M:%S')  %>
                <% else %>
                <%= "DNF" %>
                <% end %>
              </td>  
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>  
</div>

app/views/results/stage_results.html.erb
<h3>
<u><%= link_to @race.name, race_path(@race) %></u>
 &nbsp;-&nbsp; 
 <u><%= link_to 'Manage Results', manage_result_path(@race) %></u>
 &nbsp;-&nbsp; 
 Stage<%= @stage.stage_no %>  
 &nbsp;-&nbsp; 
 <%= @stage.name %> 
</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th>Strava Activity URL</th>
      <th>Avg Watts</th>
      <th>Avg Watts per Kg</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cyclists.each_with_index do |cyclist| %>
    <% stage_effort = cyclist.stage_efforts.find_by(stage_id: @stage) %>
      <tr>
        <td><%= link_to cyclist.name, cyclist.strava_athlete_url %></td>
        <% if stage_effort %>
          <td><%= Time.at(stage_effort.elapsed_time).utc.strftime('%H:%M:%S') if stage_effort.elapsed_time %></td>
          <td><%= link_to stage_effort.strava_activity_url, stage_effort.strava_activity_url %></td>    
          <td><%= stage_effort.segment_avg_watts.to_f.round(2) %>&nbsp;w</td>
          <% temp = stage_effort.segment_avg_watts.to_f / cyclist.weight.to_f unless cyclist.weight.to_f == 0 %>
          <td><%= temp.to_f.round(2) %>&nbsp;w/kg</td>
          <td><%= link_to 'Update Result', edit_stage_effort_path(@race, @stage, cyclist, stage_effort) %></td>        
          <td><%= link_to 'Remove', destroy_stage_effort_path(@race, @stage, cyclist, stage_effort), method: :delete, data: { confirm: 'Are you sure?' } %></td>          
        <%else%>
          <td></td>
          <td></td>    
          <td><%= link_to 'Add Result', new_stage_effort_path(@race, @stage, cyclist) %></td>    
          <td></td>
        <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="row">
  <div class="col-md-3"><h3>Stage Leaderboard</h3></div>
  <div class="col-md-9">
    <h3>
      <button type="button" class="btn btn-default export-btn" data-toggle="modal" data-target="#myModal">
        Export
      </button>
    </h3>
  </div>  
</div>
<div class="modal fade" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Leaderboard Export</h4>
      </div>
      <div class="modal-body">
        <textarea class="export-textarea" rows="30" cols="78">
          
        </textarea>
      </div>      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
  $('.export-btn').click(function(){
    var table_data = $('table.stage-leaderboard').html();
    var custom_style = "<style>\n .hftable { width:100%; border-collapse: collapse;}\n  th, td { text-align: left; border: 1px solid gray; padding: 5px; }\n</style>\n";
    table_data = custom_style + "<table class='hftable'>" + table_data + "</table>";
    $('.export-textarea').text(table_data);
  });
</script>

<table class="table table-striped stage-leaderboard">
  <thead>
    <tr>
      <th>Place</th>
      <th>Points</th>
      <th>Name</th>
      <th>Total time</th>
    </tr>
  </thead>

  <tbody>
    <% 
    index_temp = 0 
    elapsed_time_temp = 0
    nil_cyclists = []
    %>
    <% @cyclists.each_with_index do |cyclist, index| %>
      <% stage_effort = cyclist.stage_efforts.find_by(stage_id: @stage) %>
      <% if stage_effort %>
        <%
        if elapsed_time_temp < stage_effort.elapsed_time.to_i
          elapsed_time_temp = stage_effort.elapsed_time.to_i
          index_temp = index + 1
        end
        %>
        <tr>
          <td><%= index_temp %></td>
          <td><%= stage_effort.points %></td>        
          <td><%= cyclist.name %></td>
          <td><%= Time.at(stage_effort.elapsed_time).utc.strftime('%H:%M:%S') if stage_effort.elapsed_time %></td>                
        </tr>
      <% else
          nil_cyclists << cyclist
        end %>
    <% end %>

    <% nil_cyclists.each_with_index do |cyclist, index| %>
        <tr>
          <td><%= index_temp + 1 %></td>
          <td><%= index_temp + 1 %></td>        
          <td><%= cyclist.name %></td>
          <td>DNF</td>                
        </tr>
    <% end %>
  </tbody>
</table>