config/routes.rb
Rails.application.routes.draw do

  get '/admin', to: 'admin#index'
  get 'admin/logout', to: 'admin#destroy'
  post 'admin/login', to: 'admin#authorize'

  get 'results(.:format)', to: 'results#index'

  get 'results/races/:id(.:format)', to: 'results#manage', as: 'manage_result'

  get 'results/races/:race_id/stages/:id(.:format)', to: 'results#stage_results', as: 'stage_results'

  #new stage_effort 
  get 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/new(.:format)', to: 'stage_efforts#new', as: 'new_stage_effort'
  post 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts(.:format)', to: 'stage_efforts#create', as: 'stage_efforts'  
  get 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id/edit(.:format)', to: 'stage_efforts#edit', as: 'edit_stage_effort'
  put 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#update'
  patch 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#update', as: 'update_stage_effort'
  delete 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#destroy', as: 'destroy_stage_effort'

  resources :cyclists
  get '/auth', to: 'sessions#create'
  get '/token_exchange', to: 'sessions#get_token', as: 'get_token'
  get '/deauth', to: 'sessions#deauth'
  #get '/deauth', to: 'sessions#reset_token'
  #resources :stage_efforts

  get '/request/athlet', to: 'request#athlet', as: 'request_athlet'
  get '/request/activity', to: 'request#activity', as: 'request_activity'

  get '/sessions/race_result/:race_id', to: 'sessions#race_result', as: 'race_result'
  
  resources :races, path: '/admin/races' do
    resources :stages, except: :index do
      resources :segments
    end
    resources :rosters, only: [:index, :create, :destroy]
  end

  delete 'rosters/:race_id/cyclist/:id', to: 'rosters#destroy', as: 'delete_roster'
  post 'rosters/create/', to: 'rosters#create', as: 'create_roster'
   
  root 'sessions#get_token'
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  default_scope {order('id')}
  belongs_to :stage
  
  include StravaClient

  validates :strava_segment_url, format: {with: /\A(https|http):\/\/www.strava.com\/segments\/\d+\z/ , message: "It's incorrect segment url"}
  #before_save :get_segment_info

  def get_segment_info(access_token)
    match_result = /\d+\z/.match(self.strava_segment_url)    
  	self.strava_segment_id = match_result[0] if match_result  
    #print "======#{self.strava_segment_id}========="
    if self.strava_segment_id
    	begin	            
        result = strava_client(access_token).retrieve_a_segment(self.strava_segment_id) 
  		rescue 
  			self.description = "Athlete id does't exist or there is an error."
  			self.length = nil
  		else
  			self.length = (result['distance'].to_f) / 1609.34 #(in mile)      		     
  		  self.description = result['name']		      
  		end 
    end
  end
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment

  # GET /segments
  # GET /segments.json
  def index
    @segments = @stage.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)
    @segment.get_segment_info(session[:access_token])
    if @segment.valid?
        @segment.stage = @stage        
    end
    respond_to do |format|
      if @segment.save                
        format.html { redirect_to race_stage_path(@race, @stage), notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else        
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }      
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update    
    respond_to do |format|
      if @segment.update(segment_params)
        @segment.get_segment_info(session[:access_token])
        @segment.save
        format.html { redirect_to race_stage_path(@race, @stage), notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to race_stage_path(@race, @stage), notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment

      @race = Race.find(params[:race_id])
      @stage = @race.stages.find(params[:stage_id]) unless @race.nil?

      if params[:id].present?
        @segment = @stage.segments.find(params[:id]) unless @stage.nil?
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:strava_segment_url)
    end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= simple_form_for([@race, @stage, @segment]) do |f| %>
  <div class="form-inputs">
    <%= f.input :strava_segment_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/segments/edit.html.erb
<%= render :template => 'stages/show' %>
<p><strong>Editing Segment</strong></p>
<%= render 'form' %>
<%= link_to 'Back', race_stage_path(@race, @stage) %>

app/views/segments/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Segments</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Strava url</th>
      <th>Description</th>
      <th>Length</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.strava_url %></td>
        <td><%= segment.description %></td>
        <td><%= segment.length %></td>
        <td><%= link_to 'Show', segment %></td>
        <td><%= link_to 'Edit', edit_segment_path(segment) %></td>
        <td><%= link_to 'Destroy', segment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segment', new_segment_path, class: 'btn btn-default btn-new' %>

app/views/segments/new.html.erb
<%= render :template => 'stages/show' %>
<p><strong>New Segment</strong></p>
<%= render 'form' %>
<%= link_to 'Back', race_stage_path(@race, @stage) %>

app/views/segments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Strava url:</strong>
  <%= @segment.strava_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @segment.description %>
</p>

<p>
  <strong>Length:</strong>
  <%= @segment.length %>
</p>

<%= link_to 'Edit', edit_segment_path(@segment) %> |
<%= link_to 'Back', segments_path %>