config/routes.rb
Rails.application.routes.draw do

  get '/admin', to: 'admin#index'
  get 'admin/logout', to: 'admin#destroy'
  post 'admin/login', to: 'admin#authorize'

  get 'results(.:format)', to: 'results#index'

  get 'results/races/:id(.:format)', to: 'results#manage', as: 'manage_result'

  get 'results/races/:race_id/stages/:id(.:format)', to: 'results#stage_results', as: 'stage_results'

  #new stage_effort 
  get 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/new(.:format)', to: 'stage_efforts#new', as: 'new_stage_effort'
  post 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts(.:format)', to: 'stage_efforts#create', as: 'stage_efforts'  
  get 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id/edit(.:format)', to: 'stage_efforts#edit', as: 'edit_stage_effort'
  put 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#update'
  patch 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#update', as: 'update_stage_effort'
  delete 'results/races/:race_id/stages/:stage_id/cyclists/:cyclist_id/stage_efforts/:id(.:format)', to: 'stage_efforts#destroy', as: 'destroy_stage_effort'

  resources :cyclists
  get '/auth', to: 'sessions#create'
  get '/token_exchange', to: 'sessions#get_token', as: 'get_token'
  get '/deauth', to: 'sessions#deauth'
  #get '/deauth', to: 'sessions#reset_token'
  #resources :stage_efforts

  get '/request/athlet', to: 'request#athlet', as: 'request_athlet'
  get '/request/activity', to: 'request#activity', as: 'request_activity'

  get '/sessions/race_result/:race_id', to: 'sessions#race_result', as: 'race_result'
  
  resources :races, path: '/admin/races' do
    resources :stages, except: :index do
      resources :segments
    end
    resources :rosters, only: [:index, :create, :destroy]
  end

  delete 'rosters/:race_id/cyclist/:id', to: 'rosters#destroy', as: 'delete_roster'
  post 'rosters/create/', to: 'rosters#create', as: 'create_roster'
   
  root 'sessions#get_token'
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  default_scope {order('stage_no')}
  validates :stage_no, uniqueness: {scope: :race_id, message: "Stage number should be unique per race"}
  validates :stage_no, presence: true

  belongs_to :race
  has_many :segments, dependent: :destroy	
  has_many :stage_efforts, dependent: :destroy
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage

  # GET /stages
  # GET /stages.json
  def index
    @stages = @race.stages
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)
    if @stage.valid?
      @stage.race = @race
    end

    respond_to do |format|
      if @stage.save
        format.html { redirect_to race_path(@race), notice: 'Stage was successfully created.' }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to race_path(@race), notice: 'Stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to race_path(@race), notice: 'Stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage      
      @race = Race.find(params[:race_id])
      if params[:id].present?
        @stage = @race.stages.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:race_id, :stage_no, :name, :active_date, :close_date)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= simple_form_for([@race, @stage]) do |f| %>
  <div class="form-inputs">
    <%= f.input :stage_no, label: 'Stage Number' %>
    <%= f.input :name %>
    <%= f.input :active_date %>
    <%= f.input :close_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<%= render :template => 'races/show' %>
<p><strong>Editing Stage</strong></p>
<%= render 'form' %>
<%= link_to 'Back', race_path(@race) %>

app/views/stages/new.html.erb
<%= render :template => 'races/show' %>
<p><strong>New Stage</strong></p>
<%= render 'form' %>
<%= link_to 'Back', race_path(@race) %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <span><u><%= link_to @stage.race.name, @race %></u></span>
  <span>-</span>
  <u>
  <span>Stage <%= @stage.stage_no %> </span>
  <span>-</span>
  <span><%= @stage.name %></span>
  </u>
  <span>-</span>
  <span>Segments</span>
  <%= link_to 'Add Segment', new_race_stage_segment_path(@race, @stage), class: 'btn btn-default btn-new'%>
</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Segment#</th>
      <th>Strava URL</th>
      <th>Description</th>
      <th>Length</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @stage.segments.each_with_index do |segment, idx| %>
      <tr>
        <td><%= idx + 1 %></td>
        <td><%= link_to segment.strava_segment_url, segment.strava_segment_url %></td>
        <td><%= segment.description %></td>
        <td><%= segment.length.round(1).to_s + ' miles' if segment.length %></td>      
        <td><%= link_to 'Update', edit_race_stage_segment_path(@race, @stage, segment) %></td>
        <td><%= link_to 'Delete', race_stage_segment_path(@race, @stage, segment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>